roomname="error"
if argument0=0 then roomname="--"
if argument0=6 then roomname="Ruins - Entrance"
if argument0=12 then roomname="Ruins - Leaf Pile"
if argument0=18 then roomname="Ruins - Mouse Hole"
if argument0=31 then roomname="Ruins - Home"
